// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_tables.sql

package database

import (
	"context"
)

const createSessionTokensTable = `-- name: CreateSessionTokensTable :exec
CREATE TABLE IF NOT EXISTS session_tokens (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    token VARCHAR(256) UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateSessionTokensTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSessionTokensTable)
	return err
}

const createUsersTable = `-- name: CreateUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(64) UNIQUE NOT NULL,
    password VARCHAR(64) NOT NULL,
    role VARCHAR(16) NOT NULL
)
`

func (q *Queries) CreateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsersTable)
	return err
}
