// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type SessionToken struct {
	ID      int64
	UserID  int64
	Token   string
	Created time.Time
}

type User struct {
	ID       int64
	Email    string
	Password string
	Role     string
}
